#@ load("@ytt:overlay", "overlay")

#@yaml/text-templated-strings
---

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  model-db:
    skip_post_install: true
    builds:
      default:
        build_dependencies:
          - revng
          #! WIP: only depending on a single rootfs/pdb for now
          - rootfs/ubuntu-24-04-x86-64/debug-info
          - pdb/x86-64
        configure: |
          mkdir -p "$BUILD_DIR"

        install: |
          function log() {
            echo "$@" > /dev/stderr;
          }

          cd "$BUILD_DIR"

          export REVNG_NO_FETCH_DEBUG_INFO=1

          ROOTS_DIR="$ORCHESTRA_ROOT/share/roots"

          rm -rf models/
          mkdir -p models

          log "Importing ELFs in roots"
          for ROOTFS_DIR in $(find "$ROOTS_DIR" -mindepth 1 -maxdepth 1 -type d); do
            ROOTFS_NAME="$(basename $ROOTFS_DIR)"
            log "Importing from $ROOTFS_NAME"

            export XDG_CACHE_HOME="$BUILD_DIR/cache"
            mkdir -p "$XDG_CACHE_HOME"

            log "Coping the symbols cache to the build directory"
            SYMBOLS_CACHE="$ROOTFS_DIR/symbols-cache"
            if test -d "$SYMBOLS_CACHE"; then
              mkdir -p "$XDG_CACHE_HOME/revng/debug-symbols/elf"
              cp -a "$SYMBOLS_CACHE"/* "$XDG_CACHE_HOME/revng/debug-symbols/elf/"
            fi

            # Find all ELFs
            ELF_COUNT=0
            for ELF_FILE in $(find "$ROOTFS_DIR" -not -path "$ROOTFS_DIR//symbols-cache/*" -type f); do
              if ! head -c 4 "$ELF_FILE" 2>/dev/null | grep -q $'\x7fELF'; then
                continue
              fi

              # WIP: limit to 5 ELFs per rootfs
              ELF_COUNT=$((ELF_COUNT + 1))
              if test "$ELF_COUNT" -gt 5; then
                break
              fi

              RELATIVE_PATH="${ELF_FILE#$ROOTFS_DIR/}"
              MODEL_NAME="$(echo "$RELATIVE_PATH" | tr '/' '-')"

              log "Importing /$RELATIVE_PATH"
              revng \
                analyze \
                import-binary \
                "$ELF_FILE" \
                -o "$BUILD_DIR/models/${ROOTFS_NAME}-${MODEL_NAME}.yml"
            done
          done

          PDB_DIR="$ORCHESTRA_ROOT/share/pdb"
          if test -d "$PDB_DIR"; then
            for PDB_ARCH_DIR in $(find "$PDB_DIR" -maxdepth 1 -mindepth 1 -type d); do
              PDB_ARCH_NAME="$(basename "$(dirname "$PDB_ARCH_DIR")")"

              # WIP: head 5
              for PDB_FILE in $(find "$PDB_ARCH_DIR" -name "*.pdb"); do
                PDB_NAME="$(basename "$PDB_FILE" .yml)"
                log "Importing $PDB_FILE"
                revng \
                  model \
                  import \
                  debug-info \
                  "$PDB_FILE" \
                  -o "$BUILD_DIR/models/windows-${PDB_ARCH_NAME}-${PDB_NAME}.yml"
              done
            done
          fi

          rm -f db.sqlite

          log "Exporting models to SQLite..."
          revng \
            model \
            export \
            sqlite \
            --db db.sqlite \
            --platform "$ROOTFS_NAME" \
            models/*.yml

          # WIP: rename db
          mkdir -p "${DESTDIR}${ORCHESTRA_ROOT}/share/revng"
          cp db.sqlite "${DESTDIR}${ORCHESTRA_ROOT}/share/revng/db.sqlite"
